version: 0.2

phases:
  install:
    commands:
      - echo "Iniciando proceso de instalación..."

  pre_build:
    commands:
      - echo "Preparando proyecto..."
      - echo "Archivos encontrados:"
      - ls -la

  build:
    commands:
      - echo "Ejecutando proceso de integración..."
      - test -f index.html
      - test -f carrito.html
      - test -f pedidos.html
      - test -f nosotros.html

  post_build:
    commands:
      - echo "Integración completada correctamente."

artifacts:
  files:
    - '**/*'